name: GitHub Metrics

on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6:00 UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Plugins
          user: vireshsolanki
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          # Optional: Add extras you want
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_threshold: 2%

          plugin_stars: yes
          plugin_followup: yes
          plugin_notable: yes
          plugin_traffic: yes
